### ISSUE TITLE
RE: binary:logistic objective probabilities

### ISSUE THREAD

**Issue by alrashid** [mwburke/xgboost-python-deploy#1]
Hi @mwburke:
For `binary:logistic` objective function, if you set `base_score` to **0** per the documentation [here](https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.XGBRegressor.intercept_), it matches with the XGB native predictions. 

Unfortunately, I can't commit code right now. But you may want to fix accordingly.

Thanks!

**Comment by mwburke** [comment]
Awesome thanks for the help! I just confirmed that the values I'm getting match and will push an updated version of the package and documentation later today.

**Comment by alrashid** [comment]
Great! Thank you for the contribution of this package.
